sp = serialPlotter('COM4', 115200, '%f%f%f%f', ...
{'x Accel', 'y Accel', 'z Accel'}, ...
{'Time (s)', 'x Accel', 'y Accel', 'z Accel'}, ...
[1, 1, 1, 1] ...
);
tic;
while (toc < 6.)
end
data = sp.getData();
delete(sp);

    