sp = BluetoothPlotter('Weimen''s Robot', '%f%d%d%f', ...
{'Input Encoder', 'Output Encoder', 'Output Motor'}, ...
{'Time (s)', 'Input Encoder', 'Output Encoder', 'Output Motor'}, ...
[1, 1, 1, 1] ...
);
tic;
while (toc < 10.)
end
data = sp.getData();
delete(sp);

    