sp = serialPlotter('COM8', 500000, '%d%f%d', ...
{'Encoder Count * 2', 'Encoder Count'}, ...
{'Time (s)', 'Output', 'Count (Rev)'}, ...
[1/1000, 1/127, 1/4096] ...
);
tic;
while (toc < 6.)
end
data = sp.getData();
delete(sp);

    